### ISSUE TITLE
README的注意事项

### ISSUE THREAD

**Issue by YechengChu** [Redcxx/Chinese-Civil-Code-Notes#2]
README.md中的
⚠️注意事项里“发邮件给我”这个链接打开是404
![Screen Shot 2020-07-24 at 20 27 47](https://user-images.githubusercontent.com/44024818/88391277-70671080-cdec-11ea-9b2a-b93a2e136d35.png)

**Comment by weilueluo** [comment]
修好了么么哒~

**Comment by YechengChu** [comment]
真棒👍
